### ISSUE TITLE
error install r2frida

### ISSUE THREAD

**Issue by muhammad2321** [radare/radare2-pm#69]
[~] r2pm install r2frida                                                                                                                                         
Already up to date.
Install Done For r2frida
[ "`readlink ext/frida`" = frida-linux-10.6.41 ] || \
	(cd ext && rm -f frida ; ln -fs frida-linux-10.6.41 frida)
make io_frida.so
make[1]: Entering directory '/root/.config/radare2/r2pm/git/r2frida'
pkg-config --cflags r_core
-I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr
g++ src/io_frida.o -o io_frida.so -shared -fPIC -lr_core -lcapstone -lr_config -lr_debug -lr_bin -lr_anal -lr_bp -lr_egg -lr_asm -lr_lang -lr_parse -lr_flag -lr_cons -lr_reg -lr_search -lr_syscall -lr_fs -lr_io -lr_socket -lr_magic -lmagic -lr_crypto -lr_hash -lr_util -lz -lzip -ldl  ext/frida/libfrida-core.a -lresolv 
/usr/bin/ld: cannot find -lzip
collect2: error: ld returned 1 exit status
Makefile:104: recipe for target 'io_frida.so' failed
make[1]: *** [io_frida.so] Error 1
make[1]: Leaving directory '/root/.config/radare2/r2pm/git/r2frida'
Makefile:70: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Build failed

**Comment by radare** [comment]
Try installing libzip? :p

**Comment by clayscode** [comment]
I also have an issue installing r2frida. 
``
Already up-to-date.
Install Done For r2frida
rm -f ext/frida
mkdir -p ext/frida--11.0.0/_
curl -Ls https://github.com/frida/frida/releases/download/11.0.0/frida-core-devkit-11.0.0--x86_64.tar.xz | xz -d | tar -C ext/frida--11.0.0/_ -xf -
xz: (stdin): File format not recognized
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Makefile:232: recipe for target 'ext/frida--11.0.0/libfrida-core.a' failed
make: *** [ext/frida--11.0.0/libfrida-core.a] Error 2
ERROR: Build failed
``

Appears that the url is wrong. When I curl https://github.com/frida/frida/releases/download/11.0.0/frida-core-devkit-11.0.0--x86_64.tar.xz, the package referenced in the install, I get a 404 error.

**Comment by radare** [comment]
try again
